version: 0.2

phases:
  install:
    commands:
      - npm i

  build:
    commands:
      - npm run build

artifacts:
  files:
    - dist/*
    - dist/css/*.css
    - dist/js/*.js
  base-directory: dist/
